# services/users-service/helm/templates/deployment.yaml
# SOMENTE UM EXEMPLO
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users-container
          image: your-registry/users-service:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080